name: Deploy to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: 106790bc-16bc-4e3a-912e-446e51bb5ad0  # Your App Registration Client ID
        tenant-id: 64f77dc5-3c66-462b-a765-7e07b045624a  # Your Azure Tenant ID
        subscription-id: 22d4c835-2db5-4ed3-a88e-f62941aec87c  # Your Subscription ID
        enable-AzPSSession: false
        environment: azurecloud
        allow-no-subscriptions: false
        audience: api://AzureADTokenExchange
        auth-type: SERVICE_PRINCIPAL

    - name: Deploy or Your Azure CLI Commands
      run: |
        az account show
