name: Build and deploy Python app to Azure Web App - 12eureka

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # Needed for Azure OIDC login
      contents: read     # Needed for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies (optional for local testing)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 106790bc-16bc-4e3a-912e-446e51bb5ad0  # Your App Registration Client ID
          tenant-id: 64f77dc5-3c66-462b-a765-7e07b045624a  # Your Azure Tenant ID
          subscription-id: 22d4c835-2db5-4ed3-a88e-f62941aec87c  # Your Subscription ID

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: '12eureka'
          slot-name: 'Production'
